# Generated by Codex on 2026-06-18

from django.db import migrations, models


def materialize_invoice_receiving_modes(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().iterator():
        update_fields = []
        if not project.evm_invoice_receiving_mode:
            project.evm_invoice_receiving_mode = project.invoice_receiving_mode
            update_fields.append("evm_invoice_receiving_mode")
        if not project.tron_invoice_receiving_mode:
            project.tron_invoice_receiving_mode = project.invoice_receiving_mode
            update_fields.append("tron_invoice_receiving_mode")
        if update_fields:
            project.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            materialize_invoice_receiving_modes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="project",
            name="evm_invoice_receiving_mode",
            field=models.CharField(
                choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                default="differ",
                help_text="EVM 网络账单收款使用钱包直收或智能合约模式。",
                verbose_name="EVM 账单收款模式",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tron_invoice_receiving_mode",
            field=models.CharField(
                choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                default="differ",
                help_text="Tron 网络账单收款使用钱包直收或智能合约模式。",
                verbose_name="Tron 账单收款模式",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="invoice_receiving_mode",
        ),
    ]
