# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stress", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stressrun",
            old_name="invoice_receiving_mode",
            new_name="evm_invoice_receiving_mode",
        ),
        migrations.AlterField(
            model_name="stressrun",
            name="evm_invoice_receiving_mode",
            field=models.CharField(
                choices=[("vault_slot", "智能合约"), ("differ", "钱包直收")],
                default="vault_slot",
                help_text="本轮 EVM 账单收款压测使用的钱包直收或智能合约模式。",
                max_length=16,
                verbose_name="EVM 账单收款模式",
            ),
        ),
    ]
