# Generated by Django 5.2.14 on 2026-06-02 10:43

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chains", "0001_initial"),
        ("currencies", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvmTxTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.PositiveBigIntegerField(verbose_name="Nonce")),
                (
                    "to",
                    common.fields.EvmAddressField(
                        db_index=True, max_length=42, verbose_name="To"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=32, verbose_name="Value"
                    ),
                ),
                ("data", models.TextField(blank=True, default="", verbose_name="Data")),
                ("gas", models.PositiveIntegerField(verbose_name="Gas")),
                (
                    "gas_price",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Gas Price"
                    ),
                ),
                (
                    "signed_payload",
                    models.TextField(
                        blank=True, default="", verbose_name="已签名链上载荷"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次尝试时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "base_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evm_task",
                        to="chains.txtask",
                        verbose_name="通用链上任务",
                    ),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.chain",
                        verbose_name="网络",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chains.address",
                        verbose_name="发送地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "链上任务",
                "verbose_name_plural": "链上任务",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="VaultSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[("deposit", "用户充币"), ("invoice", "账单收款")],
                        db_index=True,
                        max_length=16,
                        verbose_name="用途",
                    ),
                ),
                (
                    "invoice_index",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="账单槽位序号"
                    ),
                ),
                (
                    "address",
                    common.fields.AddressField(
                        db_index=True, max_length=100, verbose_name="收款地址"
                    ),
                ),
                (
                    "salt",
                    models.BinaryField(max_length=32, verbose_name="CREATE2 Salt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "deploy_tx_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployed_vault_slot",
                        to="evm.evmtxtask",
                        verbose_name="部署交易任务",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "收款地址",
                "verbose_name_plural": "收款地址",
            },
        ),
        migrations.CreateModel(
            name="DepositVaultSlot",
            fields=[],
            options={
                "verbose_name": "充币收款地址",
                "verbose_name_plural": "充币收款地址",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("evm.vaultslot",),
        ),
        migrations.CreateModel(
            name="InvoiceVaultSlot",
            fields=[],
            options={
                "verbose_name": "账单收款地址",
                "verbose_name_plural": "账单收款地址",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("evm.vaultslot",),
        ),
        migrations.CreateModel(
            name="VaultSlotCollectSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(db_index=True, verbose_name="计划执行时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="currencies.crypto",
                        verbose_name="币种",
                    ),
                ),
                (
                    "tx_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_slot_collect_schedule",
                        to="evm.evmtxtask",
                        verbose_name="链上任务",
                    ),
                ),
                (
                    "vault_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collect_schedules",
                        to="evm.vaultslot",
                        verbose_name="收款地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "收款地址归集计划",
                "verbose_name_plural": "收款地址归集计划",
                "ordering": ("due_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="EvmScanCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_scanned_block",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已扫描到的区块"
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="最近错误"),
                ),
                (
                    "last_error_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近错误时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evm_scan_cursors",
                        to="chains.chain",
                        verbose_name="链",
                    ),
                ),
            ],
            options={
                "verbose_name": "EVM 扫描游标",
                "verbose_name_plural": "EVM 扫描游标",
                "ordering": ("chain_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain",), name="uniq_evm_scan_cursor_chain"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="evmtxtask",
            constraint=models.UniqueConstraint(
                fields=("sender", "chain", "nonce"),
                name="uniq_evm_tx_task_sender_chain_nonce",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("customer", "chain"), name="uniq_evm_vault_slot_customer_chain"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("project", "usage", "chain", "invoice_index"),
                name="uniq_evm_vault_slot_project_usage_chain_invoice_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.UniqueConstraint(
                fields=("chain", "address"), name="uniq_evm_vault_slot_chain_address"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("invoice_index__isnull", True),
                        ("usage", "deposit"),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("invoice_index__isnull", False),
                        ("usage", "invoice"),
                    ),
                    _connector="OR",
                ),
                name="ck_evm_vault_slot_usage_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="vaultslotcollectschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tx_task__isnull", True)),
                fields=("chain", "vault_slot", "crypto"),
                name="uniq_pending_vault_slot_collect",
            ),
        ),
    ]
