# Generated by Django 5.2.12 on 2026-05-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evm", "0008_contractdeploycollection_recipient_rename"),
        ("invoices", "0012_invoice_billing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractdeploycollection",
            name="pay_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_deploy_collections",
                to="invoices.invoicepayslot",
            ),
        ),
    ]
